apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  selector:
    matchLabels:
      app: expiration
  replicas: 1
  template:
    metadata:
      labels:
        app: expiration
    spec:
      # initContainers:
      containers:
        - name: expiration
          image: hjpunzalan/ticket-expiration
          # imagePullPolicy: Always
          env:
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            - name: REDIS_HOST
              value: expiration-redis-srv
